name: dart_dsa
description: Implementations of the most common data structures and algorithms in the Dart programming language!
version: 1.0.0
repository: https://github.com/Speedstrike/dart_dsa

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
